name: Walkthrough of Life
favicon: null
layout_spectrum: 0.41834
typography_spectrum: 0.28025
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
