name: Walkthrough of Life
favicon: null
layout_spectrum: 0.2734302328899503
typography_spectrum: 0.4689292174298316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6120506783481687
  lightness: 0.03430099133402109
  saturation: 0.6878536210861057
  rhythmicContrast: 0.11001341207884252
purpose: []
